#!/bin/bash

##################
#Author:Himanshu
#Date:22Nov
#
#Version:v1
#
#This script will report the AWS resource usage
#####################


#AWS S3
#AWS EC2
#AWS Lambda
#AWS IAM Users

#list s3 buckets
echo "S3 buckets"
aws s3 ls


echo "EC2 instances"
#list EC2 Instances
aws ec2 describe-instances


echo "Lambda functions"
#lis lambda
aws lambda list-functions

echo "IAM users"
#list IAM users
aws iam list-users

